<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Master Wallet Audit Ledger - {{ $date }}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 0; background: #fff; }
        #printable-area { padding: 40px; }
        .header { text-align: center; border-bottom: 2px solid #192C57; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #192C57; margin: 0; font-size: 24px; }
        .header p { color: #777; margin: 5px 0 0 0; }
        .summary-box { background: #f8f9fa; border: 1px solid #ddd; padding: 15px; text-align: center; margin-bottom: 30px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; font-size: 14px; }
        th { background-color: #192C57; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .text-right { text-align: right; }
        .amount { font-weight: bold; color: #192C57; }
        .type-badge { font-size: 11px; text-transform: uppercase; color: #555; }
    </style>
</head>
<body>

    <div id="printable-area">
        <div class="header">
            <h1>KCA PEAKS HOTEL</h1>
            <p>Master Wallet Audit Ledger (All Transfers & Purchases)</p>
            <p><strong>Date Filter:</strong> {{ \Carbon\Carbon::parse($date)->format('F d, Y') }}</p>
        </div>

        <div class="summary-box">
            Total Wallet Volume Moved on this Date: KES {{ number_format($totalTransferred) }}
        </div>

        <table>
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Type</th>
                    <th>Deducted From</th>
                    <th>Sent To</th>
                    <th>Description</th>
                    <th class="text-right">Amount (KES)</th>
                </tr>
            </thead>
            <tbody>
                @forelse($transactions as $tx)
                <tr>
                    <td>{{ $tx->created_at->format('h:i A') }}</td>
                    <td class="type-badge">
                        @if($tx->type == 'admin_override') Admin Override
                        @elseif($tx->type == 'food_purchase') Meal Purchase
                        @else Staff Transfer
                        @endif
                    </td>
                    <td>{{ $tx->sender_name }}</td>
                    <td>{{ $tx->receiver_name }}</td>
                    <td style="font-size: 12px; color: #666;">{{ $tx->description }}</td>
                    <td class="text-right amount">{{ number_format($tx->amount) }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" style="text-align: center; color: #999;">No wallet activity found for this date.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

        <div style="margin-top: 50px; font-size: 12px; color: #777; text-align: center;">
            <p>Generated by KCA Cafeteria Order Management System on {{ now()->format('Y-m-d H:i:s') }}</p>
        </div>
    </div>

    <script>
        window.onload = function() {
            const action = "{{ $action ?? 'print' }}";

            if (action === 'download') {
                const element = document.getElementById('printable-area');
                const opt = {
                    margin:       0.5,
                    filename:     'KCA_Wallet_Ledger_{{ $date }}.pdf',
                    image:        { type: 'jpeg', quality: 0.98 },
                    html2canvas:  { scale: 2 },
                    jsPDF:        { unit: 'in', format: 'a4', orientation: 'portrait' }
                };
                
                // Generate PDF and instantly save it
                html2pdf().set(opt).from(element).save().then(() => {
                    // Optional: Automatically close the tab 1 second after download finishes
                    setTimeout(() => window.close(), 1000); 
                });
            } else {
                // Regular Print Mode
                window.print();
            }
        };
    </script>
</body>
</html>